---
kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: uname
  image: ubuntu:trusty
  commands:
  - uname -a

- name: dist
  image: python:3.8-alpine
  commands:
  - scripts/download-dist

- name: deb
  image: arescentral/deb

- name: check
  image: ubuntu:trusty
  commands:
  - dpkg -i gn_*.deb
  - gn --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "*.deb"
    - "*.dsc"
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: uname
  image: debian@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b
  commands:
  - uname -a

- name: dist
  image: python:3.8-alpine
  commands:
  - scripts/download-dist

- name: deb
  image: arescentral/deb

- name: check
  image: debian@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b
  commands:
  - dpkg -i gn_*.deb
  - gn --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "*.deb"
    - "*.dsc"
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: uname
  image: debian:stretch-slim
  commands:
  - uname -a

- name: dist
  image: python:3.8-alpine
  commands:
  - scripts/download-dist

- name: deb
  image: arescentral/deb

- name: check
  image: debian:stretch-slim
  commands:
  - dpkg -i gn_*.deb
  - gn --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "*.deb"
    - "*.dsc"
  when:
    event:
    - tag

...
