---
{
   "kind": "pipeline",
   "name": "checks",
   "steps": [
      {
         "commands": [
            "jsonnetfmt .drone.jsonnet | diff -u .drone.jsonnet -",
            "jsonnet -y .drone.jsonnet | diff -u .drone.yml -"
         ],
         "image": "bitnami/jsonnet:0.16.0",
         "name": "jsonnet"
      }
   ],
   "type": "docker"
}
---
{
   "depends_on": [
      "checks"
   ],
   "kind": "pipeline",
   "name": "debian/amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "arescentral/deb-buster",
         "name": "deb/buster",
         "settings": {
            "dir": "buster"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*buster_*.deb",
            "gn --version"
         ],
         "image": "debian:buster-slim",
         "name": "check/buster"
      },
      {
         "image": "arescentral/deb-buster",
         "name": "deb/stretch",
         "settings": {
            "dir": "stretch"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*stretch_*.deb",
            "gn --version"
         ],
         "image": "debian:stretch-slim",
         "name": "check/stretch"
      },
      {
         "image": "plugins/github-release",
         "name": "publish",
         "settings": {
            "api_key": {
               "from_secret": "github_token"
            },
            "files": [
               "gn_*.deb",
               "gn_*.dsc"
            ]
         },
         "when": {
            "event": "tag"
         }
      }
   ],
   "type": "docker"
}
---
{
   "depends_on": [
      "checks"
   ],
   "kind": "pipeline",
   "name": "debian/arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "arescentral/deb-buster",
         "name": "deb/buster",
         "settings": {
            "dir": "buster"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*buster_*.deb",
            "gn --version"
         ],
         "image": "debian:buster-slim",
         "name": "check/buster"
      },
      {
         "image": "arescentral/deb-buster",
         "name": "deb/stretch",
         "settings": {
            "dir": "stretch"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*stretch_*.deb",
            "gn --version"
         ],
         "image": "debian:stretch-slim",
         "name": "check/stretch"
      },
      {
         "image": "plugins/github-release",
         "name": "publish",
         "settings": {
            "api_key": {
               "from_secret": "github_token"
            },
            "files": [
               "gn_*.deb"
            ]
         },
         "when": {
            "event": "tag"
         }
      }
   ],
   "type": "docker"
}
---
{
   "depends_on": [
      "checks"
   ],
   "kind": "pipeline",
   "name": "debian/arm",
   "platform": {
      "arch": "arm",
      "os": "linux"
   },
   "steps": [
      {
         "image": "arescentral/deb-buster",
         "name": "deb/buster",
         "settings": {
            "dir": "buster"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*buster_*.deb",
            "gn --version"
         ],
         "image": "debian@sha256:43e8691b4e25f4b0fd0f10bca8ea11b9f0578b0e5d2fe3b085290455dd07c0b6",
         "name": "check/buster"
      },
      {
         "image": "arescentral/deb-buster",
         "name": "deb/stretch",
         "settings": {
            "dir": "stretch"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*stretch_*.deb",
            "gn --version"
         ],
         "image": "debian@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b",
         "name": "check/stretch"
      },
      {
         "image": "plugins/github-release",
         "name": "publish",
         "settings": {
            "api_key": {
               "from_secret": "github_token"
            },
            "files": [
               "gn_*.deb"
            ]
         },
         "when": {
            "event": "tag"
         }
      }
   ],
   "type": "docker"
}
---
{
   "depends_on": [
      "checks"
   ],
   "kind": "pipeline",
   "name": "ubuntu/amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "arescentral/deb-focal",
         "name": "deb/focal",
         "settings": {
            "dir": "focal"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*focal_*.deb",
            "gn --version"
         ],
         "image": "ubuntu:focal",
         "name": "check/focal"
      },
      {
         "image": "arescentral/deb-bionic",
         "name": "deb/bionic",
         "settings": {
            "dir": "bionic"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*bionic_*.deb",
            "gn --version"
         ],
         "image": "ubuntu:bionic",
         "name": "check/bionic"
      },
      {
         "image": "arescentral/deb-bionic",
         "name": "deb/xenial",
         "settings": {
            "dir": "xenial"
         }
      },
      {
         "commands": [
            "uname -a",
            "dpkg -i gn_*xenial_*.deb",
            "gn --version"
         ],
         "image": "ubuntu:xenial",
         "name": "check/xenial"
      },
      {
         "image": "plugins/github-release",
         "name": "publish",
         "settings": {
            "api_key": {
               "from_secret": "github_token"
            },
            "files": [
               "gn_*.deb",
               "gn_*.dsc"
            ]
         },
         "when": {
            "event": "tag"
         }
      }
   ],
   "type": "docker"
}
...
