#!/usr/bin/env python3

import os
import json
import shutil
import urllib.request

GN_REPO = "sfiera/gn"


def main():
    try:
        shutil.rmtree("dist")
    except FileNotFoundError:
        pass
    os.mkdir("dist")

    with open("release.json") as f:
        release = json.load(f)
    asset, = release["assets"]
    path = os.path.join("dist", asset["name"])
    with urllib.request.urlopen(asset["browser_download_url"]) as src:
        with open(path, "wb") as dst:
            shutil.copyfileobj(src, dst)
    print("Downloaded %s" % path)


if __name__ == "__main__":
    main()
